apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vapi.fullname" . }}
  labels:
    {{- include "vapi.labels" . | nindent 4 }}
data:
  APP_NAME: "Laravel"
  APP_ENV: "local"
  APP_KEY: "base64:JUXTsCKQubRlvxGv6sVwkFL2rJ/gSksD4B/68948Mww="
  APP_DEBUG: "true"
  APP_URL: https://example.local
  SERVER_PORT: "80"
  LOG_CHANNEL: "errorlog"
  LOG_LEVEL: "debug"
  DB_CONNECTION: "mysql"
  DB_HOST: "vapi-mysql"
  DB_PORT: "3306"
  DB_DATABASE: "vapi"
  BROADCAST_DRIVER: "log"
  CACHE_DRIVER: "file"
  FILESYSTEM_DRIVER: "local"
  QUEUE_CONNECTION: "sync"
  SESSION_DRIVER: "file"
  SESSION_LIFETIME: "120"
  MEMCACHED_HOST: "127.0.0.1"
  REDIS_HOST: "127.0.0.1"
  REDIS_PASSWORD: ""
  REDIS_PORT: "6379"
  MAIL_MAILER: "smtp"
  MAIL_HOST: "mailhog"
  MAIL_PORT: "1025"
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
  MAIL_ENCRYPTION: ""
  MAIL_FROM_ADDRESS: ""
  MAIL_FROM_NAME: "vapi"
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_BUCKET: ""
  AWS_USE_PATH_STYLE_ENDPOINT: "false"
  PUSHER_APP_ID: ""
  PUSHER_APP_KEY: ""
  PUSHER_APP_SECRET: ""
  PUSHER_APP_CLUSTER: "mt1"
  MIX_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
  MIX_PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}"


